### PR TITLE
Skip fiber-geometry model when simulating DWIs

### LINKED ISSUE #29: Skip fiber-geometry model
Hi @ecaruyer, is it possible with/without modifications of phantomas to simulate the dwi signal from dyads as generated by Bedpost? This means: we have voxel-wise information of the orientations of up-to 3 fibers, and then the corresponding volume of each.

### PR DESCRIPTION
**Pull request by oesteban**
When merged (if merged), close #29 .

### CODE REVIEW

**Comment by oesteban** [comment]
@ecaruyer: finally it was easier than I thought. Could you check my code?. If you are happy with this code, it is ready to merge: I'm having a result with this (still need to run reconstruction on these data). But it doesn't look very bad.

**Comment by ecaruyer** [comment]
Sorry for replying that late... Would you be OK to move this script to the examples folder? Also please add a reference to your recent Frontiers paper. Thanks!

**Comment by oesteban** [comment]
No problem :). Will do ASAP

**Comment by oesteban** [comment]
@ecaruyer there you go!

**Pull request merged**
